export const attackLabels = { MELEE: '近战', RANGED: '远程', BALANCED: '均衡', DEFENSE: '防御' }
export const talentLabels = { MEDIOCRE: '平庸', COMMON: '普通', GOOD: '良好', EXCELLENT: '优秀', PERFECT: '完美' }
export const sourceLabels = { VERIFIED: '已核实', ESTIMATED: '待核实', DIY: '自定义' }
export const nodeLabels = { OUTPOST: '据点', WILD: '野地', DUNGEON: '副本', SYSTEM_CITY: '系统城', RANDOM_CITY: '随机城池' }
export const statusLabels: Record<string,string> = { ACTIVE:'进行中', PAUSED:'已暂停', TARGET_GONE:'目标已消失，正在返城',COMPLETED:'已完成', FAILED:'失败', MARCHING:'行军中', FIGHTING:'战斗中', RETURNING:'返城中', CANCELLED:'已取消', VICTORY:'胜利', DEFEAT:'战败', DRAW:'平局', DEPLETED:'已耗尽', LOCKED:'未开放' }
export const effectLabels:Record<string,string> = { MELEE_DEFENSE_PERCENT:'近防提升',RANGED_DEFENSE_PERCENT:'远防提升',DEFENSE_PERCENT:'双防提升',MELEE_DEFENSE_REDUCE:'削弱敌军近防',RANGED_DEFENSE_REDUCE:'削弱敌军远防',ALL_STATS_PERCENT:'全攻全防提升',ENEMY_ALL_STATS_REDUCE:'削弱敌方全攻全防',ESCAPE_CAPTURE:'逃脱俘虏',CAPTURE_BONUS:'俘虏加成',CULTURE_BONUS:'文韬武略加成',CULTURE_REDUCE:'削弱文韬武略',TECH_DEFENSE_PERCENT:'护甲科技加成',ENEMY_TECH_ATTACK_REDUCE:'削弱攻击科技',ENEMY_TECH_DEFENSE_REDUCE:'削弱护甲科技',CLAN_ATTACK_PERCENT:'家族攻击加成',CLAN_DEFENSE_PERCENT:'家族防御加成',ENEMY_CLAN_DEFENSE_REDUCE:'削弱家族防御',ENEMY_CLAN_ATTACK_REDUCE:'削弱家族攻击',LOSS_REDUCTION_DEFEAT:'败战减损',LOSS_REDUCTION:'战后减损',PROTECT_RESOURCES:'保护城内资源',IGNORE_STORAGE:'无视密库',STORAGE_BONUS:'密库容量加成',PVE_ATTACK_PERCENT:'据点野地副本攻击提升',PVE_DEFENSE_REDUCE:'削弱据点野地副本防御',PVE_EXPERIENCE:'据点野地副本额外经验', ATTACK_PERCENT:'全攻提升', MELEE_ATTACK_PERCENT:'近攻提升', RANGED_ATTACK_PERCENT:'远攻提升', TECH_ATTACK_PERCENT:'科技攻击加成', ENEMY_MELEE_ATTACK_REDUCE:'削弱敌军近攻', ENEMY_RANGED_ATTACK_REDUCE:'削弱敌军远攻', ATTACK_REDUCE:'削弱敌军全攻', DEFENSE_REDUCE:'削弱敌军防御', IGNORE_DEFENSE:'穿透防御', EXPERIENCE_PERCENT:'经验提升' }
export const targetLabels:Record<string,string> = {SELF_ALL:'我方全部兵种',ENEMY_ALL:'敌方全军',FORT_ONE:'我方一个城防',FORT_ALL:'我方全部城防',ENEMY_FORT_ONE:'敌方一个城防',ENEMY_FORT_ALL:'敌方全部城防',HERO_SELF:'本英雄',ENEMY_HERO:'敌方一个英雄', SELF:'我方全军', SELF_ONE:'我方一个兵种', ENEMY:'敌方全军', ENEMY_ONE:'敌方一个兵种' }
export const modeLabels = { ATTACK:'进攻时', DEFENSE:'防守时', BOTH:'攻防皆可' }
export const currencyLabels = { food:'粮食', wood:'木材', stone:'石料', iron:'铁矿', gold:'金币', coupon:'点券', heroExp:'英雄经验' }
export function label(map:Record<string,string>,value?:string|null):string { return value ? (map[value] ?? '未配置') : '无' }
