// Generated by scripts/import-official-catalog.mjs from the official catalog.
export const officialCatalog = {
  "source": "https://zg.qq.com/act/a20100623tbsq/suit_photo.htm",
  "heroSource": "https://zg.qq.com/act/a20100623tbsq/hero_intro.htm",
  "heroes": [
    {
      "name": "秦始皇",
      "star": 6
    },
    {
      "name": "屈原",
      "star": 6
    },
    {
      "name": "孙武",
      "star": 6
    },
    {
      "name": "庄子",
      "star": 6
    },
    {
      "name": "范蠡",
      "star": 6
    },
    {
      "name": "管仲",
      "star": 6
    },
    {
      "name": "伍子胥",
      "star": 6
    },
    {
      "name": "张良",
      "star": 6
    },
    {
      "name": "越女",
      "star": 6
    },
    {
      "name": "养由基",
      "star": 6
    },
    {
      "name": "章邯",
      "star": 6
    },
    {
      "name": "鬼谷子",
      "star": 6
    },
    {
      "name": "黄石公",
      "star": 6
    },
    {
      "name": "赤松子",
      "star": 6
    },
    {
      "name": "荀子",
      "star": 6
    },
    {
      "name": "李斯",
      "star": 6
    },
    {
      "name": "扁鹊",
      "star": 6
    },
    {
      "name": "庞涓",
      "star": 6
    },
    {
      "name": "冒顿单于",
      "star": 6
    },
    {
      "name": "欧冶子",
      "star": 6
    },
    {
      "name": "齐桓公",
      "star": 6
    },
    {
      "name": "宋襄公",
      "star": 6
    },
    {
      "name": "晋文公",
      "star": 6
    },
    {
      "name": "楚庄王",
      "star": 6
    },
    {
      "name": "吴王阖闾",
      "star": 6
    },
    {
      "name": "越王勾践",
      "star": 6
    }
  ],
  "sets": [
    {
      "name": "地载套装",
      "star": 3,
      "icons": [
        "/art/official/trea_8000.jpg",
        "/art/official/trea_8001.jpg",
        "/art/official/trea_8002.jpg",
        "/art/official/trea_8003.jpg",
        "/art/official/trea_8004.jpg",
        "/art/official/trea_8005.jpg",
        "/art/official/trea_8006.jpg",
        "/art/official/trea_8007.jpg"
      ]
    },
    {
      "name": "炎舞套装",
      "star": 3,
      "icons": [
        "/art/official/trea_8008.jpg",
        "/art/official/trea_8009.jpg",
        "/art/official/trea_8010.jpg",
        "/art/official/trea_8011.jpg",
        "/art/official/trea_8012.jpg",
        "/art/official/trea_8013.jpg",
        "/art/official/trea_8014.jpg",
        "/art/official/trea_8015.jpg"
      ]
    },
    {
      "name": "雷霆套装",
      "star": 3,
      "icons": [
        "/art/official/trea_8016.jpg",
        "/art/official/trea_8017.jpg",
        "/art/official/trea_8018.jpg",
        "/art/official/trea_8019.jpg",
        "/art/official/trea_8020.jpg",
        "/art/official/trea_8021.jpg",
        "/art/official/trea_8022.jpg",
        "/art/official/trea_8023.jpg"
      ]
    },
    {
      "name": "丰泽套装",
      "star": 3,
      "icons": [
        "/art/official/trea_8024.jpg",
        "/art/official/trea_8025.jpg",
        "/art/official/trea_8026.jpg",
        "/art/official/trea_8027.jpg",
        "/art/official/trea_8028.jpg",
        "/art/official/trea_8029.jpg",
        "/art/official/trea_8030.jpg",
        "/art/official/trea_8031.jpg"
      ]
    },
    {
      "name": "疾风套装",
      "star": 3,
      "icons": [
        "/art/official/trea_8032.jpg",
        "/art/official/trea_8033.jpg",
        "/art/official/trea_8034.jpg",
        "/art/official/trea_8035.jpg",
        "/art/official/trea_8036.jpg",
        "/art/official/trea_8037.jpg",
        "/art/official/trea_8038.jpg",
        "/art/official/trea_8039.jpg"
      ]
    },
    {
      "name": "玄武套装",
      "star": 4,
      "icons": [
        "/art/official/trea_9000.jpg",
        "/art/official/trea_9001.jpg",
        "/art/official/trea_9002.jpg",
        "/art/official/trea_9003.jpg",
        "/art/official/trea_9004.jpg",
        "/art/official/trea_9005.jpg",
        "/art/official/trea_9006.jpg",
        "/art/official/trea_9007.jpg"
      ]
    },
    {
      "name": "寒铁套装",
      "star": 4,
      "icons": [
        "/art/official/trea_9008.jpg",
        "/art/official/trea_9009.jpg",
        "/art/official/trea_9010.jpg",
        "/art/official/trea_9011.jpg",
        "/art/official/trea_9012.jpg",
        "/art/official/trea_9013.jpg",
        "/art/official/trea_9014.jpg",
        "/art/official/trea_9015.jpg"
      ]
    },
    {
      "name": "天雷套装",
      "star": 4,
      "icons": [
        "/art/official/trea_9016.jpg",
        "/art/official/trea_9017.jpg",
        "/art/official/trea_9018.jpg",
        "/art/official/trea_9019.jpg",
        "/art/official/trea_9020.jpg",
        "/art/official/trea_9021.jpg",
        "/art/official/trea_9022.jpg",
        "/art/official/trea_9023.jpg"
      ]
    },
    {
      "name": "麒麟套装",
      "star": 4,
      "icons": [
        "/art/official/trea_9024.jpg",
        "/art/official/trea_9025.jpg",
        "/art/official/trea_9026.jpg",
        "/art/official/trea_9027.jpg",
        "/art/official/trea_9028.jpg",
        "/art/official/trea_9029.jpg",
        "/art/official/trea_9030.jpg",
        "/art/official/trea_9031.jpg"
      ]
    },
    {
      "name": "白虎套装",
      "star": 4,
      "icons": [
        "/art/official/trea_9032.jpg",
        "/art/official/trea_9033.jpg",
        "/art/official/trea_9034.jpg",
        "/art/official/trea_9035.jpg",
        "/art/official/trea_9036.jpg",
        "/art/official/trea_9037.jpg",
        "/art/official/trea_9038.jpg",
        "/art/official/trea_9039.jpg"
      ]
    },
    {
      "name": "神舞套装",
      "star": 5,
      "icons": [
        "/art/official/trea_10000.jpg",
        "/art/official/trea_10001.jpg",
        "/art/official/trea_10002.jpg",
        "/art/official/trea_10003.jpg",
        "/art/official/trea_10004.jpg",
        "/art/official/trea_10005.jpg",
        "/art/official/trea_10006.jpg",
        "/art/official/trea_10007.jpg"
      ]
    },
    {
      "name": "魔怒套装",
      "star": 5,
      "icons": [
        "/art/official/trea_10008.jpg",
        "/art/official/trea_10009.jpg",
        "/art/official/trea_10010.jpg",
        "/art/official/trea_10011.jpg",
        "/art/official/trea_10012.jpg",
        "/art/official/trea_10013.jpg",
        "/art/official/trea_10014.jpg",
        "/art/official/trea_10015.jpg"
      ]
    },
    {
      "name": "狂神套装",
      "star": 5,
      "icons": [
        "/art/official/trea_10016.jpg",
        "/art/official/trea_10017.jpg",
        "/art/official/trea_10018.jpg",
        "/art/official/trea_10019.jpg",
        "/art/official/trea_10020.jpg",
        "/art/official/trea_10021.jpg",
        "/art/official/trea_10022.jpg",
        "/art/official/trea_10023.jpg"
      ]
    },
    {
      "name": "星魂套装",
      "star": 5,
      "icons": [
        "/art/official/trea_10024.jpg",
        "/art/official/trea_10025.jpg",
        "/art/official/trea_10026.jpg",
        "/art/official/trea_10027.jpg",
        "/art/official/trea_10028.jpg",
        "/art/official/trea_10029.jpg",
        "/art/official/trea_10030.jpg",
        "/art/official/trea_10031.jpg"
      ]
    },
    {
      "name": "鬼烈套装",
      "star": 5,
      "icons": [
        "/art/official/trea_10032.jpg",
        "/art/official/trea_10033.jpg",
        "/art/official/trea_10034.jpg",
        "/art/official/trea_10035.jpg",
        "/art/official/trea_10036.jpg",
        "/art/official/trea_10037.jpg",
        "/art/official/trea_10038.jpg",
        "/art/official/trea_10039.jpg"
      ]
    }
  ],
  "singles": [
    {
      "name": "突厥马",
      "star": 3,
      "icon": "/art/official/trea_8040.jpg"
    },
    {
      "name": "蒙古马",
      "star": 3,
      "icon": "/art/official/trea_8041.jpg"
    },
    {
      "name": "凉州马",
      "star": 3,
      "icon": "/art/official/trea_8042.jpg"
    },
    {
      "name": "河曲马",
      "star": 3,
      "icon": "/art/official/trea_8043.jpg"
    },
    {
      "name": "西戎马",
      "star": 3,
      "icon": "/art/official/trea_8044.jpg"
    },
    {
      "name": "漠北马",
      "star": 3,
      "icon": "/art/official/trea_8045.jpg"
    },
    {
      "name": "云龙盘丝甲",
      "star": 3,
      "icon": "/art/official/trea_8046.jpg"
    },
    {
      "name": "玄铁盾",
      "star": 3,
      "icon": "/art/official/trea_8047.jpg"
    },
    {
      "name": "名器·真刚",
      "star": 3,
      "icon": "/art/official/trea_8048.jpg"
    },
    {
      "name": "名器·却邪",
      "star": 3,
      "icon": "/art/official/trea_8049.jpg"
    },
    {
      "name": "名器·断水",
      "star": 3,
      "icon": "/art/official/trea_8050.jpg"
    },
    {
      "name": "名器·灭魂",
      "star": 3,
      "icon": "/art/official/trea_8051.jpg"
    },
    {
      "name": "名器·转魄",
      "star": 3,
      "icon": "/art/official/trea_8052.jpg"
    },
    {
      "name": "名器·悬剪",
      "star": 3,
      "icon": "/art/official/trea_8053.jpg"
    },
    {
      "name": "名器·掩日",
      "star": 3,
      "icon": "/art/official/trea_8054.jpg"
    },
    {
      "name": "名器·惊鲵",
      "star": 3,
      "icon": "/art/official/trea_8055.jpg"
    },
    {
      "name": "七名马·追风",
      "star": 4,
      "icon": "/art/official/trea_9040.jpg"
    },
    {
      "name": "七名马·白兔",
      "star": 4,
      "icon": "/art/official/trea_9041.jpg"
    },
    {
      "name": "七名马·蹑景",
      "star": 4,
      "icon": "/art/official/trea_9042.jpg"
    },
    {
      "name": "七名马·追电",
      "star": 4,
      "icon": "/art/official/trea_9043.jpg"
    },
    {
      "name": "七名马·飞翩",
      "star": 4,
      "icon": "/art/official/trea_9044.jpg"
    },
    {
      "name": "七名马·铜爵",
      "star": 4,
      "icon": "/art/official/trea_9045.jpg"
    },
    {
      "name": "七名马·晨凫",
      "star": 4,
      "icon": "/art/official/trea_9046.jpg"
    },
    {
      "name": "六甲金钟",
      "star": 4,
      "icon": "/art/official/trea_9047.jpg"
    },
    {
      "name": "离火玄冰",
      "star": 4,
      "icon": "/art/official/trea_9048.jpg"
    },
    {
      "name": "惊雷",
      "star": 4,
      "icon": "/art/official/trea_9049.jpg"
    },
    {
      "name": "千钧",
      "star": 4,
      "icon": "/art/official/trea_9050.jpg"
    },
    {
      "name": "断岳",
      "star": 4,
      "icon": "/art/official/trea_9051.jpg"
    },
    {
      "name": "燎原",
      "star": 4,
      "icon": "/art/official/trea_9052.jpg"
    },
    {
      "name": "苦行",
      "star": 4,
      "icon": "/art/official/trea_9053.jpg"
    },
    {
      "name": "穆王八骏·绝地",
      "star": 5,
      "icon": "/art/official/trea_10040.jpg"
    },
    {
      "name": "穆王八骏·翻羽",
      "star": 5,
      "icon": "/art/official/trea_10041.jpg"
    },
    {
      "name": "穆王八骏·奔霄",
      "star": 5,
      "icon": "/art/official/trea_10042.jpg"
    },
    {
      "name": "穆王八骏·超影",
      "star": 5,
      "icon": "/art/official/trea_10043.jpg"
    },
    {
      "name": "穆王八骏·逾辉",
      "star": 5,
      "icon": "/art/official/trea_10044.jpg"
    },
    {
      "name": "穆王八骏·超光",
      "star": 5,
      "icon": "/art/official/trea_10045.jpg"
    },
    {
      "name": "穆王八骏·胜雾",
      "star": 5,
      "icon": "/art/official/trea_10046.jpg"
    },
    {
      "name": "穆王八骏·挟翼",
      "star": 5,
      "icon": "/art/official/trea_10047.jpg"
    },
    {
      "name": "法相琉璃",
      "star": 5,
      "icon": "/art/official/trea_10048.jpg"
    },
    {
      "name": "巡天曜日旗",
      "star": 5,
      "icon": "/art/official/trea_10049.jpg"
    },
    {
      "name": "幻神",
      "star": 5,
      "icon": "/art/official/trea_10050.jpg"
    },
    {
      "name": "镇狱",
      "star": 5,
      "icon": "/art/official/trea_10051.jpg"
    },
    {
      "name": "轮回",
      "star": 5,
      "icon": "/art/official/trea_10052.jpg"
    },
    {
      "name": "痴狂",
      "star": 5,
      "icon": "/art/official/trea_10053.jpg"
    },
    {
      "name": "离别",
      "star": 5,
      "icon": "/art/official/trea_10054.jpg"
    }
  ]
} as const
