// 腾讯官方《英雄技能》2010年页面的44项10级数值；低级插值为单机估算。
// https://zg.qq.com/webplat/info/173/641/1365/201012/85358.shtml
export const officialSkills = [
 ['rexue','热血','MELEE_ATTACK_PERCENT','SELF_ONE','ATTACK',60,60,3,'赤红刀锋，热血火焰'],
 ['jingzhun','精准','RANGED_ATTACK_PERCENT','SELF_ONE','ATTACK',60,60,3,'蓝银箭矢命中靶心'],
 ['guwu','鼓舞','ATTACK_PERCENT','SELF_ONE','ATTACK',70,70,4,'金色战鼓和两支鼓槌，昂扬战意'],
 ['kuangre','狂热','ATTACK_PERCENT','SELF_ALL','ATTACK',100,70,7,'燃烧的猩红战旗，三道金色枪锋'],
 ['naili','耐力','MELEE_DEFENSE_PERCENT','SELF_ONE','DEFENSE',60,60,3,'青铜圆盾抵挡沉重战斧，深绿色光芒'],
 ['duoshan','躲闪','RANGED_DEFENSE_PERCENT','SELF_ONE','DEFENSE',60,60,3,'敏捷武士的青色残影闪过三支箭'],
 ['tiejia','铁甲','MELEE_DEFENSE_PERCENT','FORT_ONE','DEFENSE',60,60,3,'铁甲覆盖的古代城门，银灰金属'],
 ['huoyao','火药','RANGED_DEFENSE_PERCENT','FORT_ONE','DEFENSE',60,60,3,'古代火药罐与烟火，城墙远景'],
 ['yelian','冶炼','DEFENSE_PERCENT','FORT_ONE','DEFENSE',60,60,4,'熔炉铁水与铸造的盾牌，橙红炽热'],
 ['tongxin','同心','DEFENSE_PERCENT','FORT_ALL','DEFENSE',100,60,6,'紧密相连的三面金色城防盾牌'],
 ['fushi','腐蚀','MELEE_DEFENSE_REDUCE','ENEMY_ONE','ATTACK',70,70,4,'被翠绿酸雾侵蚀的青铜盾牌'],
 ['chuanci','穿刺','RANGED_DEFENSE_REDUCE','ENEMY_ONE','ATTACK',70,70,4,'紫蓝利箭穿透铠甲'],
 ['jiaoxie','缴械','ENEMY_MELEE_ATTACK_REDUCE','ENEMY_ONE','DEFENSE',60,60,3,'断裂落下的古代刀剑，冷白震击'],
 ['miwu','迷雾','ENEMY_RANGED_ATTACK_REDUCE','ENEMY_ONE','DEFENSE',60,60,3,'迷雾吞没的弓箭和浅青色旋涡'],
 ['xiejia','卸甲','MELEE_DEFENSE_REDUCE','ENEMY_FORT_ONE','ATTACK',60,70,4,'被剥落铁甲的古代城门，黄色冲击'],
 ['lianjin','炼金','RANGED_DEFENSE_REDUCE','ENEMY_FORT_ONE','ATTACK',60,70,4,'金色炼金坩埚向城墙喷出绿焰'],
 ['qianggong','强攻','DEFENSE_REDUCE','ENEMY_FORT_ONE','ATTACK',70,70,5,'巨型攻城槌撞破古代城门'],
 ['miejue','灭绝','DEFENSE_REDUCE','ENEMY_FORT_ALL','ATTACK',70,70,6,'赤黑烈焰摧毁一片古代城防塔楼'],
 ['xinnian','信念','ATTACK_PERCENT','HERO_SELF','ATTACK',70,100,5,'武将握紧金色长剑，太阳光环'],
 ['zhengjiu','拯救','DEFENSE_PERCENT','HERO_SELF','DEFENSE',70,100,5,'将领身前展开金青色守护盾'],
 ['lingdaoli','领导力','ALL_STATS_PERCENT','HERO_SELF','BOTH',70,100,7,'威严青铜虎符与金色令旗'],
 ['xiedai','懈怠','DEFENSE_REDUCE','ENEMY_HERO','ATTACK',70,100,5,'垂落的头盔与迟钝灰紫雾气'],
 ['angyang','昂扬','ATTACK_REDUCE','ENEMY_HERO','DEFENSE',70,100,5,'金色咆哮狮纹盾牌压下敌方剑锋'],
 ['baquan','霸权','ENEMY_ALL_STATS_REDUCE','ENEMY_HERO','BOTH',70,100,6,'漆黑玉玺投下强烈赤金威压'],
 ['dunzou','遁走','ESCAPE_CAPTURE','HERO_SELF','BOTH',100,100,5,'迅疾战马冲出铁链包围，青白风痕'],
 ['lijian','离间','CAPTURE_BONUS','ENEMY_HERO','BOTH',70,100,5,'两枚敌对青铜虎符被紫色裂缝分开'],
 ['fengci','封赐','CULTURE_BONUS','SELF_ALL','BOTH',100,60,6,'帝王赐下金色册书与红绶带'],
 ['beipan','背叛','CULTURE_REDUCE','ENEMY_ALL','BOTH',100,60,6,'背后刺出的黑色短刃，紫红破碎令旗'],
 ['xueyuan','学院','TECH_ATTACK_PERCENT','SELF_ALL','ATTACK',100,70,6,'金色竹简兵书和交叉弓剑'],
 ['tengjia','藤甲','TECH_DEFENSE_PERCENT','SELF_ALL','DEFENSE',100,60,6,'编织藤甲被青绿保护光芒包裹'],
 ['tiebi','铁壁','ENEMY_TECH_ATTACK_REDUCE','ENEMY_ALL','DEFENSE',100,70,6,'厚重黑铁城墙抵挡金色箭雨'],
 ['huojianshu','火箭术','ENEMY_TECH_DEFENSE_REDUCE','ENEMY_ALL','ATTACK',100,60,6,'带火焰的古代箭矢斜贯画面'],
 ['zhongcheng','忠诚','CLAN_ATTACK_PERCENT','SELF_ALL','ATTACK',100,70,5,'紧握红色盟誓战旗的青铜手甲'],
 ['weifeng','威风','CLAN_DEFENSE_PERCENT','SELF_ALL','DEFENSE',100,60,5,'威武狮面铠甲和风中金色旗帜'],
 ['fanjian','反间','ENEMY_CLAN_DEFENSE_REDUCE','ENEMY_ALL','ATTACK',100,70,5,'隐秘竹简中露出细刃，紫色计谋烟雾'],
 ['liuyan','流言','ENEMY_CLAN_ATTACK_REDUCE','ENEMY_ALL','DEFENSE',100,60,5,'飞散卷宗与灰紫色耳语旋风'],
 ['zhiliao','治疗','LOSS_REDUCTION_DEFEAT','SELF_ALL','BOTH',100,30,4,'古代药钵与绷带，柔和翠绿疗愈光'],
 ['zhanzheng_guanghuan','战争光环','LOSS_REDUCTION','SELF_ALL','BOTH',100,30,7,'金色环形光辉包围三面青铜战盾'],
 ['yinbi','隐蔽','PROTECT_RESOURCES','SELF_ALL','DEFENSE',100,100,4,'薄雾遮住粮仓与资源箱，暗绿色'],
 ['qiangduo','强夺','IGNORE_STORAGE','ENEMY_ALL','ATTACK',100,60,4,'铁手甲攫取粮袋和金锭，橙色冲击'],
 ['jiliang','积粮','STORAGE_BONUS','SELF_ALL','DEFENSE',100,60,4,'饱满麦穗与紧闭的青铜粮仓'],
 ['kongju','恐惧','PVE_ATTACK_PERCENT','SELF_ALL','ATTACK',100,35,6,'猩红鬼面战旗发出震慑波纹'],
 ['feijiang','飞将','PVE_DEFENSE_REDUCE','ENEMY_ALL','ATTACK',100,35,6,'飞驰战马上的将军举起长枪，金白速度线'],
 ['lingwu','领悟','PVE_EXPERIENCE','HERO_SELF','BOTH',100,60,5,'展开的竹简中升起璀璨金色智慧光芒'],
] as const
