<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {api} from './api'
import {useTimedNotice} from './timed-notice'
import type {IncomingRaidRules} from '../shared/incoming-raids'
import {bossLootLabels} from '../shared/world-boss'
const form=ref<IncomingRaidRules>(),percent=ref(0),busy=ref(false),failed=ref(false),notice=useTimedNotice()
async function load(){if(busy.value)return;busy.value=true;try{form.value=await api('/api/admin/incoming-army');percent.value=form.value!.itemChance*100;failed.value=false}catch(e){failed.value=true;notice.value=e instanceof Error?e.message:'读取失败'}finally{busy.value=false}}
async function save(){if(busy.value||!form.value)return;busy.value=true;try{form.value=await api('/api/admin/incoming-army',{method:'PUT',body:JSON.stringify({...form.value,itemChance:percent.value/100})});notice.value='来袭军队规则已保存'}catch(e){notice.value=e instanceof Error?e.message:'保存失败'}finally{busy.value=false}}
onMounted(load)
</script>
<template><section class="raid-settings"><h3>来袭军队 · 外部调用</h3><p>不内置定时调度。外部服务每调用一次接口，生成一支随机军队，5分钟游戏时间后攻击主城。规则仅影响新军队，关闭生成不会取消已经出发的敌军。</p><code>/api/admin/tasks/spawn-incoming-army/run</code>
<form v-if="form" @submit.prevent="save"><fieldset :disabled="busy"><div class="raid-controls"><button type="button" role="switch" :aria-checked="form.enabled" aria-label="允许生成来袭军队" :class="{active:form.enabled}" @click="form.enabled=!form.enabled">{{form.enabled?'来袭接口：已开启':'来袭接口：已关闭'}}</button><label>总攻击力下限<input v-model.number="form.attackMin" aria-label="来袭攻击下限" type="number" min="1" :max="form.attackMax" required></label><label>总攻击力上限<input v-model.number="form.attackMax" aria-label="来袭攻击上限" type="number" :min="form.attackMin" max="10000000000" required></label><label>每种物品掉率（%）<input v-model.number="percent" aria-label="防守物品掉率" type="number" min="0" max="100" step="0.1" required></label></div>
<p>攻击方向随机为近攻、远攻或混攻。留城士兵与已建成城防按满科技双防参战；不包含在途、训练中的部队和英雄。战力相等则双方全灭；强方损失按人数×战力比平方向下取整。</p>
<div class="raid-quantities"><label v-for="(name,key) in bossLootLabels" :key="key"><span>{{name}}每种数量</span><input v-model.number="form.quantities[key].min" type="number" min="1" :max="form.quantities[key].max" :aria-label="'防守'+name+'数量下限'" required><span>～</span><input v-model.number="form.quantities[key].max" type="number" :min="form.quantities[key].min" max="10000" :aria-label="'防守'+name+'数量上限'" required></label></div>
<p>防守胜利后，全目录已上架物品逐种独立抽取并自动入包；宝石仅各类一级。平局、败战无掉落，不额外扣除仓库资源。</p><button class="primary">保存来袭规则</button></fieldset></form><button v-if="failed" :disabled="busy" @click="load">重新读取</button><p v-if="notice" class="toast" role="status">{{notice}}</p></section></template>
<style scoped>.raid-settings{padding:18px 20px;margin:18px 0;border:1px solid #8b5a3b;background:linear-gradient(120deg,#30221c,#151c14);box-shadow:inset 0 0 0 3px #10160e}.raid-settings h3{color:#edba70;margin:0 0 10px}.raid-settings p{color:#b9ab88;font-size:12px;line-height:1.8}.raid-settings code{display:block;color:#dabd77;overflow-wrap:anywhere;margin-bottom:15px}.raid-settings fieldset{border:0;padding:0;min-width:0}.raid-controls{display:flex;gap:16px;align-items:end;flex-wrap:wrap}.raid-controls label{font-size:12px}.raid-controls input{display:block;width:145px;margin-top:7px}.raid-controls .active{border-color:#be8a4c;color:#f6d48c}.raid-quantities{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 25px;margin:16px 0}.raid-quantities label{display:flex;align-items:center;gap:8px;font-size:12px;color:#d0bc86}.raid-quantities label>span:first-child{flex:1}.raid-quantities input{width:88px;margin:0}@media(max-width:680px){.raid-quantities{grid-template-columns:1fr}}</style>
