<script setup lang="ts">
import GameSelect from './GameSelect.vue'

import {labelOptions,qualityOptions} from './select-options'
import {computed,onMounted,reactive,ref} from 'vue'
import type {WorldStatus} from '../shared/contracts'
import {equipmentSlots,itemTypes,type ItemDefinition,type DropPool} from '../shared/items'
import {defaultGrowth,statLabels,type GrowthRules} from '../shared/hero-growth'
import {talentLabels,nodeLabels} from '../shared/labels'
import {qualityLabels} from '../shared/quality'
import {api,actionId} from './api'
import {useTimedNotice} from './timed-notice'
import AssetIcon from './AssetIcon.vue'
import ItemEffectFields from './ItemEffectFields.vue'
import ForgeSettings from './ForgeSettings.vue'
import {MAX_DROP_QUANTITY} from '../shared/drop-rules'
const effectInvalid=ref(false),showTrash=ref(false)
const props=defineProps<{world:WorldStatus}>(),emit=defineEmits<{changed:[];editSkill:[number]}>()
const items=ref<ItemDefinition[]>([]),pools=ref<DropPool[]>([]),growth=reactive<GrowthRules>(structuredClone(defaultGrowth)),tab=ref<'inventory'|'catalog'|'drops'|'growth'>('catalog'),search=ref(''),kind=ref(''),busy=ref(false),error=useTimedNotice(),message=useTimedNotice()
const form=reactive<any>({}),pool=ref<DropPool>()
function newItem(){Object.assign(form,{id:0,deletedAt:null,code:'',name:'',itemType:'EQUIPMENT',rarity:1,qualityTier:1,enabled:true,description:'',effectConfig:{slot:'HELMET',bonuses:{},sourceStatus:'DIY'}})}
function changeType(){form.effectConfig={sourceStatus:'DIY',...(form.itemType==='EQUIPMENT'?{slot:'HELMET',bonuses:{}}:form.itemType==='TREASURE'?{bonuses:{}}:form.itemType==='CONSUMABLE'?{kind:'EXPERIENCE',amount:500}:{})}}
function edit(i:ItemDefinition){Object.assign(form,structuredClone(i));form.effectConfig.bonuses??={};tab.value='catalog'}
async function load(){const [i,p,g]=await Promise.all([api<ItemDefinition[]>('/api/admin/items'),api<DropPool[]>('/api/admin/drop-pools'),api<GrowthRules>('/api/admin/growth')]);items.value=i;pools.value=p;Object.assign(growth,g);if(!pool.value&&p[0])editPool(p[0]);else if(pool.value)for(const item of i)if(!pool.value.entries.some(e=>e.itemId===item.id))pool.value.entries.push({itemId:item.id,weight:10,minQuantity:1,maxQuantity:1,enabled:false})}
function editPool(p:DropPool){pool.value=structuredClone(p);for(const item of items.value)if(!pool.value.entries.some(e=>e.itemId===item.id))pool.value.entries.push({itemId:item.id,weight:10,minQuantity:1,maxQuantity:1,enabled:false})}
const filtered=computed(()=>items.value.filter(i=>Boolean(i.deletedAt)===showTrash.value&&(i.name+i.description).includes(search.value)&&(!kind.value||i.itemType===kind.value)))
async function action(fn:()=>Promise<void>,text:string){if(busy.value)return;busy.value=true;error.value='';message.value='';try{await fn();message.value=text;await load();emit('changed')}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
async function save(){await action(async()=>{const body={...form,code:form.code||'item_'+actionId()};const r=await api<{id:number}>(form.id?'/api/admin/items/'+form.id:'/api/admin/items',{method:form.id?'PUT':'POST',body:JSON.stringify(body)});form.id=r.id;form.code=body.code},'物品已保存；已装备物品的属性同步生效')}
async function archive(){if(!form.id||busy.value)return;await action(async()=>{await api('/api/admin/items/'+form.id,{method:'DELETE'});newItem()},'物品已移入回收站，藏宝阁会自动同步；原有库存和装备保留')}
async function restore(){await action(async()=>{await api('/api/admin/items/'+form.id+'/restore',{method:'POST'});newItem();showTrash.value=false},'物品已恢复；按原有启用状态重新展示与掉落')}
async function savePool(){if(!pool.value)return;await action(async()=>{await api('/api/admin/drop-pools/'+pool.value!.id,{method:'PUT',body:JSON.stringify(pool.value)})},'掉落池已保存，后续战斗按新配置抽取')}
function item(id:number){return items.value.find(i=>i.id===id)}
function chance(id:number){const p=pool.value;if(!p||!p.enabled)return '0';const valid=p.entries.filter(e=>e.enabled&&item(e.itemId)?.enabled),total=valid.reduce((n,e)=>n+e.weight,0),e=valid.find(e=>e.itemId===id);return total&&e?(p.chance*e.weight/total*100).toFixed(2):'0'}
onMounted(()=>{newItem();void action(load,'')})
</script>
<template><div class="detail-tabs"><button v-for="t in (['inventory','catalog','drops','growth'] as const)" :key="t" :class="{active:tab===t}" @click="tab=t">{{{inventory:'我的仓库',catalog:'物品目录',drops:'随机掉落池',growth:'成长规则'}[t]}}</button></div><p v-if="error" class="toast error">{{error}}</p><p v-if="message" class="toast">{{message}}</p>
  <div v-if="tab==='inventory'" class="hero-detail-pane"><p class="fineprint">在武将详情页使用道具、装备和宝物。技能书在技能槽中学习或升级；交易功能暂未开放。</p><div class="grid-table"><article v-for="entry in world.inventory" :key="entry.gear?-entry.gear.instanceId:entry.item.id" class="record skill"><AssetIcon :name="entry.item.name" :image-url="entry.item.effectConfig.icon" :icon-key="entry.item.itemType==='SKILL_BOOK'?entry.item.code.replace('skill_book_',''):undefined" :quality="entry.item.qualityTier"/><div><b>{{entry.item.name}} ×{{entry.quantity}}</b><p class="skill-description">{{entry.item.description}}</p></div><button disabled data-game-hint="交易尚未开放">交易</button></article></div><p v-if="!world.inventory.length" class="empty">仓库暂无物品，可在酒馆获取技能书、攻打据点获得道具。</p></div>
  <div v-if="tab==='catalog'" class="hero-detail-pane"><div class="quality-legend"><span v-for="tier in 7" :key="tier" :class="'quality-'+(8-tier)">{{qualityLabels[8-tier]}}</span></div><div class="item-admin-layout"><div><div class="learn-row"><input v-model="search" placeholder="搜索物品" aria-label="搜索物品"><GameSelect v-model="kind" label="物品分类" :options="[{id:'',label:'所有物品'},...labelOptions(itemTypes)]"/></div><div class="detail-tabs"><button :class="{active:!showTrash}" @click="showTrash=false;newItem()">物品目录</button><button :class="{active:showTrash}" @click="showTrash=true;newItem()">回收站</button></div><p class="fineprint">{{showTrash?'回收站':'目录'}} {{filtered.length}} 项；藏宝阁与此目录共用数据，前台自动同步。回收站保留已有库存和培养进度。</p><div class="item-list"><button v-for="i in filtered" :key="i.id" @click="edit(i)"><AssetIcon :name="i.name" :image-url="i.effectConfig.icon" :icon-key="i.itemType==='SKILL_BOOK'?i.code.replace('skill_book_',''):undefined" :quality="i.qualityTier" size="tiny"/><span><b>{{i.name}}</b><small>{{itemTypes[i.itemType]}} · {{qualityLabels[i.qualityTier??i.rarity]}} · {{i.deletedAt?'已删除':i.enabled?'启用':'停用'}}</small></span></button></div></div>
    <form @submit.prevent="save"><h3>{{form.id?'编辑':'新增'}}物品 <button type="button" @click="newItem">新增另一件</button></h3><template v-if="form.deletedAt"><p class="fineprint">该物品已移入回收站，藏宝阁不再显示，停止新掉落与新穿戴。已有库存、穿戴属性、精炼和宝石保留。</p><button class="primary" type="button" :disabled="busy" @click="restore">恢复物品</button></template><template v-else-if="form.itemType==='SKILL_BOOK'"><p class="fineprint">技能书与技能目录保持同一份定义；掉落池和库存从这里统一选择。名称、说明、效果请编辑对应技能。</p><button type="button" @click="emit('editSkill',form.effectConfig.skillId)">编辑技能资料</button></template><template v-else><div class="fields"><label>名称<input v-model="form.name" required maxlength="64"></label><label>类别<GameSelect v-model="form.itemType" label="物品类别" :options="labelOptions(itemTypes).filter(o=>o.id!=='SKILL_BOOK')" :disabled="Boolean(form.id)" @update:model-value="changeType"/></label><label>品质<GameSelect v-model="form.qualityTier" label="品质" :options="qualityOptions"/></label><label>星级<input v-model.number="form.rarity" type="number" min="1" max="6" required></label><label v-if="form.itemType==='EQUIPMENT'">装备位置<GameSelect v-model="form.effectConfig.slot" label="装备部位" :options="labelOptions(equipmentSlots).filter(o=>!o.id.startsWith('TREASURE_')&&!o.id.endsWith('_2'))" :disabled="Boolean(form.id)"/></label><template v-if="['EQUIPMENT','TREASURE'].includes(form.itemType)"><label v-for="(name,key) in statLabels">{{name}}加成（%）<input v-model.number="form.effectConfig.bonuses[key]" type="number" min="0" max="1000" step="0.1" placeholder="0"></label></template><template v-if="form.itemType==='CONSUMABLE'"><label>用途<GameSelect v-model="form.effectConfig.kind" label="道具用途" :options="labelOptions({TALENT:'天赋洗练',EXPERIENCE:'增加经验',STAMINA:'恢复体力',RENAME:'英雄改名'})"/></label><label v-if="!['TALENT','RENAME'].includes(form.effectConfig.kind)">数值<input v-model.number="form.effectConfig.amount" type="number" min="1" max="1000000" required></label><template v-else-if="form.effectConfig.kind==='TALENT'"><label v-for="(name,key) in talentLabels">{{name}}权重<input :value="form.effectConfig.talentWeights?.[key]??({MEDIOCRE:15,COMMON:40,GOOD:28,EXCELLENT:14,PERFECT:3}[key])" @input="form.effectConfig.talentWeights??={MEDIOCRE:15,COMMON:40,GOOD:28,EXCELLENT:14,PERFECT:3};form.effectConfig.talentWeights[key]=Number(($event.target as HTMLInputElement).value)" type="number" min="0" max="100000" required></label></template></template><label><input v-model="form.enabled" type="checkbox">启用（停用后不再掉落）</label></div><label>物品说明<textarea v-model="form.description" required maxlength="4000"></textarea></label><ItemEffectFields :form="form" @invalid="effectInvalid=$event"/><div class="button-row"><button class="primary" :disabled="busy||effectInvalid">保存物品</button><button v-if="form.id&&['EQUIPMENT','TREASURE'].includes(form.itemType)" type="button" class="danger-button" :disabled="busy" @click="archive">删除 · 移入回收站</button></div></template></form></div></div>
  <form v-if="tab==='drops'&&pool" class="hero-detail-pane" @submit.prevent="savePool"><div class="learn-row"><h3>配置掉落池</h3><GameSelect :model-value="pool.id" @update:model-value="id=>editPool(pools.find(p=>p.id===id)!)" label="掉落池" :options="pools.map(p=>({id:p.id,label:p.name}))"/></div><div class="fields"><label>名称<input v-model="pool.name" required maxlength="64"></label><label>战斗目标<GameSelect v-model="pool.nodeType" label="战斗目标" :options="labelOptions(nodeLabels)"/></label><label>最低等级<input v-model.number="pool.minLevel" type="number" min="1" max="100" required></label><label>最高等级<input v-model.number="pool.maxLevel" type="number" :min="pool.minLevel" max="100" required></label><label>掉落概率（0—1）<input v-model.number="pool.chance" type="number" step="0.01" min="0" max="1" required></label><label>独立抽选次数<input v-model.number="pool.rolls" type="number" min="1" max="10" required></label><label><input v-model="pool.enabled" type="checkbox">启用掉落池</label></div><p class="fineprint">仅胜利掉落，普通出征和自动刷野共用。每次抽选按权重选择一种物品，数量在最少与最多之间等概率随机（含两端，上限 {{MAX_DROP_QUANTITY}}）；停用物品不会进入随机池。据点最高20级：1级按基础概率的25%生效，逐级提升，20级达到100%；下面列出20级或其他目标的每次抽选概率。</p><div class="drop-entry"><b>物品 / 基础单次概率</b><small>权重</small><small>最少</small><small>最多</small></div><div v-for="e in pool.entries" :key="e.itemId" class="drop-entry"><label><input v-model="e.enabled" type="checkbox" :disabled="!item(e.itemId)?.enabled">{{item(e.itemId)?.name}} · {{chance(e.itemId)}}%</label><input v-model.number="e.weight" :aria-label="item(e.itemId)?.name+'权重'" type="number" min="1" max="1000000" required><input v-model.number="e.minQuantity" aria-label="最少数量" type="number" min="1" :max="Math.min(e.maxQuantity,MAX_DROP_QUANTITY)" required><input v-model.number="e.maxQuantity" aria-label="最多数量" type="number" :min="e.minQuantity" :max="MAX_DROP_QUANTITY" required></div><button class="primary" :disabled="busy">保存掉落池</button></form>
  <form v-if="tab==='growth'" class="hero-detail-pane" @submit.prevent="action(async()=>{await api('/api/admin/growth',{method:'PUT',body:JSON.stringify({...growth,sourceStatus:'DIY'})})},'成长规则已更新')"><h3>英雄成长曲线</h3><p class="fineprint">属性 =（一级基础 × 成长倍率 ＋ 装备固定属性 ＋ 宝石属性）×（1 ＋ 百分比加成）。战斗成长倍率为 1 +（等级²−1）× 战斗成长系数 × 星级系数 × 天赋系数。负重、速度采用逐级线性增长。修改会即时影响所有现有武将，包括已派出武将的后续战斗；已在途行军时间不重算。此公式是待校准估算，并非官方逐级表。</p><div class="fields"><label>战斗成长系数<input v-model.number="growth.combatRate" type="number" step="0.001" min="0.001" max="10" required></label><label>负重每级系数<input v-model.number="growth.loadRate" type="number" step="0.001" min="0" max="10" required></label><label>速度每级系数<input v-model.number="growth.speedRate" type="number" step="0.001" min="0" max="1" required></label><label v-for="(_,index) in growth.starFactors">{{index+1}} 星系数<input v-model.number="growth.starFactors[index]" type="number" step="0.01" min="0.01" max="10" required></label><label v-for="(name,key) in talentLabels">{{name}}系数<input v-model.number="growth.talentFactors[key]" type="number" step="0.01" min="0.01" max="10" required></label></div><button class="primary" :disabled="busy">保存成长规则</button></form>
<ForgeSettings v-if="tab==='growth'"/>
</template>
