<script setup lang="ts">
import {computed,reactive} from 'vue'
import type {Wallet} from '../shared/contracts'
import {MAX_MILITARY_ORDER_QUANTITY,durationText,speedupGoldCost,type MilitaryOrder,type MilitaryState,type MilitaryKind,type MilitaryDefinition} from '../shared/military'
import {currencyLabels} from '../shared/labels'
import UnitBadge from './UnitBadge.vue'
const props=defineProps<{state:MilitaryState;kind:MilitaryKind;wallet:Wallet;gameTime:number;busy:boolean}>()
const emit=defineEmits<{order:[code:string,quantity:number];speedup:[orderId:number,maxGold:number]}>(),quantities=reactive<Record<string,number>>({})
const definitions=computed(()=>props.state.definitions.filter(d=>d.kind===props.kind&&(d.enabled||props.state.stock[d.code]>0)))
const orders=computed(()=>props.state.orders.filter(o=>o.kind===props.kind))
const stockTotal=computed(()=>definitions.value.reduce((total,d)=>total+(props.state.stock[d.code]??0),0))
const verb=computed(()=>props.kind==='TROOP'?'招募':'建造')
const quantity=(code:string)=>quantities[code]??1
const maxAffordable=(d:MilitaryDefinition)=>Math.min(MAX_MILITARY_ORDER_QUANTITY,...Object.entries(d.cost).filter(([,n])=>n!>0).map(([k,n])=>Math.floor((props.wallet[k as keyof Wallet]??0)/n!)))
const valid=(d:MilitaryDefinition)=>Number.isSafeInteger(quantity(d.code))&&quantity(d.code)>0&&quantity(d.code)<=maxAffordable(d)
function order(d:MilitaryDefinition){if(props.busy||!d.enabled||!valid(d)||orders.value.length>=50)return;emit('order',d.code,quantity(d.code))}
function waiting(start:string){return new Date(start).getTime()>props.gameTime}
const accelerationPrice=(order:MilitaryOrder)=>speedupGoldCost(order,props.gameTime)
function accelerate(order:MilitaryOrder){const price=accelerationPrice(order);if(props.busy||price<=0||props.wallet.gold<price)return;emit('speedup',order.id,price)}
</script>
<template>
 <div class="section-title"><div><small>{{kind==='TROOP'?'军营满级 · 科技全满':'城内建筑满级 · 城防逐座营造'}}</small><h1>{{kind==='TROOP'?'军营点兵':'城防营造'}}</h1></div><p>关闭浏览器后继续生产 · 按游戏时间结算</p></div>
 <p v-if="!state.ready" class="error">兵种数据库尚未更新，请先运行 npm run db:update:military。</p>
 <template v-else>
 <section class="garrison-overview" aria-label="当前驻城数量"><header><h3>{{kind==='TROOP'?'当前城内兵力':'当前已建城防'}}</h3><span>合计 <b>{{stockTotal.toLocaleString()}}</b></span></header><div class="garrison-units"><div v-for="d in definitions" :key="d.code" class="garrison-unit"><UnitBadge :code="d.code" :name="d.name"/><span>{{d.name}}<b>{{(state.stock[d.code]??0).toLocaleString()}}</b></span></div></div><small>{{kind==='TROOP'?'显示城内可用士兵，出征中的兵力不计入；招募完成、返城和战损结算后自动更新。':'显示已经建成的城防，队列中尚未完成的数量不计入。'}}</small></section>
 <div v-if="kind==='DEFENSE'" class="military-summary"><span>驻城总近防 <b>{{state.defense.melee.toLocaleString()}}</b></span><span>驻城总远防 <b>{{state.defense.ranged.toLocaleString()}}</b></span><span>留城武将 <b>{{state.defense.heroes?.length??0}} 位</b></span><small>留城武将、士兵与已建城防合计，含满科技及武将天赋、装备、宝石和套装；技能在迎敌时按概率发动。出征、返程及自动刷野中的武将不参与。</small><div v-if="state.defense.heroes?.length" class="home-heroes"><span v-for="hero in state.defense.heroes" :key="hero.heroId"><b>{{hero.name}}</b><small>近防 {{hero.meleeDefense.toLocaleString()}} · 远防 {{hero.rangedDefense.toLocaleString()}}</small></span></div></div>
 <div class="production-queue"><h3>{{verb}}队列 <small>{{orders.length}} / 50</small></h3><p v-if="!orders.length" class="fineprint">队列空闲，选择下方{{kind==='TROOP'?'兵种':'城防'}}安排{{verb}}。</p><article v-for="o in orders" :key="o.id"><div><b>{{o.name}} × {{o.quantity.toLocaleString()}}</b><span>{{waiting(o.startGameAt)?'排队中':'生产中'}} · 已完成 {{o.completed}} / {{o.quantity}}</span></div><progress :value="o.completed" :max="o.quantity" :aria-label="o.name+'生产进度'"></progress><div class="queue-finish"><small>{{waiting(o.startGameAt)?'等待 '+durationText((new Date(o.startGameAt).getTime()-gameTime)/1000)+' 后开始':'下一单位 '+durationText(Math.max(0,(new Date(o.startGameAt).getTime()+(o.completed+1)*o.seconds*1000-gameTime)/1000))}} · 全部完成还需 {{durationText((new Date(o.endGameAt).getTime()-gameTime)/1000)}}</small><button class="primary speedup-button" :disabled="busy||accelerationPrice(o)<=0||wallet.gold<accelerationPrice(o)" :aria-label="o.name+'金币加速'" @click="accelerate(o)">{{accelerationPrice(o)<=0?'完成结算中…':'立即完成 · '+accelerationPrice(o).toLocaleString()+' 金币'}}</button></div></article><p class="fineprint">同类订单依次生产，士兵逐个入营、城防逐座生效；招募与城防两条队列独立并行。金币加速按剩余生产时间每5分钟1金币，不足5分钟按1金币；只收本单生产时间，后续同类订单自动提前。</p></div>
 <div class="military-grid"><article v-for="d in definitions" :key="d.code" class="military-card"><header><UnitBadge :code="d.code" :name="d.name"/><div><small>{{d.role}}</small><h2>{{d.name}}</h2><b class="unit-stock">{{kind==='TROOP'?'城内可用':'已建成'}} {{(state.stock[d.code]??0).toLocaleString()}}</b></div></header><p>{{d.description}}</p><dl class="unit-stats"><template v-if="kind==='TROOP'"><div><dt>近攻</dt><dd>{{d.meleeAttack.toLocaleString()}}</dd></div><div><dt>远攻</dt><dd>{{d.rangedAttack.toLocaleString()}}</dd></div></template><div><dt>近防</dt><dd>{{d.meleeDefense.toLocaleString()}}</dd></div><div><dt>远防</dt><dd>{{d.rangedDefense.toLocaleString()}}</dd></div><template v-if="kind==='TROOP'"><div><dt>速度</dt><dd>{{d.speed.toLocaleString()}}</dd></div><div><dt>负重</dt><dd>{{d.loadCapacity.toLocaleString()}}</dd></div></template></dl><small class="fineprint">单单位基础属性 · 近远攻防享受满科技加成</small><div class="unit-price"><span v-for="(cost,key) in d.cost" v-show="cost" :key="key" :class="{gold:key==='gold'}">{{currencyLabels[key]}} {{cost?.toLocaleString()}}</span><strong v-if="d.kind==='TROOP'">每个耗粮 {{d.foodPerHour??0}} / 游戏小时</strong><strong>单个耗时 {{durationText(d.seconds)}}</strong></div><div class="recruit-row"><label>数量<input :value="quantity(d.code)" type="number" min="1" :max="MAX_MILITARY_ORDER_QUANTITY" :aria-label="d.name+verb+'数量'" @input="quantities[d.code]=Number(($event.target as HTMLInputElement).value)"></label><button type="button" :disabled="busy||!d.enabled||maxAffordable(d)<1" @click="quantities[d.code]=Math.max(1,maxAffordable(d))">最多{{MAX_MILITARY_ORDER_QUANTITY}}</button><button class="primary" :disabled="busy||!d.enabled||!valid(d)||orders.length>=50" @click="order(d)">{{!d.enabled?'已停用':valid(d)?verb:'资源不足或数量无效'}}</button></div><small>本批耗时 {{durationText(d.seconds*Math.max(0,quantity(d.code)))}}<template v-if="(d.cost.gold??0)>0"> · 共 {{((d.cost.gold??0)*Math.max(0,quantity(d.code))).toLocaleString()}} 金币</template></small></article></div>
 </template>
</template>
<style scoped>
.garrison-overview{margin-bottom:18px;padding:16px 20px;border:1px solid #77633e;background:linear-gradient(125deg,#292d1f,#151d15);box-shadow:inset 0 1px #bca36133}.garrison-overview>header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:12px}.garrison-overview h3{margin:0;color:#e6c77d;font-size:18px;font-weight:normal}.garrison-overview>header b{color:#f0d990;font-size:22px;margin-left:8px}.garrison-units{display:grid;grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:10px}.garrison-unit{display:flex;align-items:center;gap:10px;padding:10px;background:#11180f;border:1px solid #4b5135}.garrison-unit>span{color:#c9c2a0;font-size:12px}.garrison-unit b{display:block;color:#ebd59a;font:600 20px/1.5 system-ui}.garrison-overview>small{display:block;color:#a59b79;font-size:11px;margin-top:12px}
.queue-finish{align-items:center;flex-wrap:wrap}.speedup-button{flex-shrink:0;padding:8px 14px;font-size:12px}.home-heroes{display:flex;flex-wrap:wrap;gap:9px;width:100%}.home-heroes>span{padding:9px 12px;border:1px solid #6b603e;background:#1e251a}.home-heroes b{margin-left:0;font-size:14px}.home-heroes small{display:block;margin-top:5px;font-size:11px}
</style>
