<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {api} from './api'
import {useTimedNotice} from './timed-notice'
import {bossLootLabels,type WorldBossRules} from '../shared/world-boss'
const form=ref<WorldBossRules>(),spawnPercent=ref(0),itemPercent=ref(0),busy=ref(false),failed=ref(false),notice=useTimedNotice()
async function load(){busy.value=true;try{form.value=await api('/api/admin/world-boss');spawnPercent.value=form.value!.spawnChance*100;itemPercent.value=form.value!.itemChance*100;failed.value=false}catch(e){failed.value=true;notice.value=e instanceof Error?e.message:'读取首领规则失败'}finally{busy.value=false}}
async function save(){if(busy.value||!form.value)return;busy.value=true;try{form.value=await api('/api/admin/world-boss',{method:'PUT',body:JSON.stringify({...form.value,spawnChance:spawnPercent.value/100,itemChance:itemPercent.value/100})});notice.value='世界首领规则已保存'}catch(e){notice.value=e instanceof Error?e.message:'保存失败'}finally{busy.value=false}}
onMounted(load)
</script>
<template><section class="boss-settings"><h3>世界首领</h3><p>刷新据点、野地或全部目标时额外抽取，同时最多一只；普通刷新不会替换首领。出现后存活5分钟（游戏时间），加速同步生效。败战不降级，首次击败或到期即消失。</p><form v-if="form" @submit.prevent="save"><fieldset :disabled="busy"><h4>首领强度 · 下次生成生效</h4><div class="boss-controls boss-strength"><label>等级<input v-model.number="form.level" aria-label="世界首领等级" type="number" min="1" max="1000" step="1" required></label><label>近战防御<input v-model.number="form.meleeDefense" aria-label="世界首领近防" type="number" min="1" max="1000000000000" step="1" required></label><label>远程防御<input v-model.number="form.rangedDefense" aria-label="世界首领远防" type="number" min="1" max="1000000000000" step="1" required></label></div><p>等级与双防分别设置；修改不会改变已经出现的首领，也不会重置其倒计时。</p><div class="boss-controls"><button type="button" role="switch" :aria-checked="form.enabled" aria-label="世界首领随机刷新" :class="{active:form.enabled}" @click="form.enabled=!form.enabled">{{form.enabled?'随机出现：已开启':'随机出现：已关闭'}}</button><label>每次刷新出现概率（%）<input v-model.number="spawnPercent" aria-label="世界首领出现概率" type="number" min="0" max="100" step="0.1" required></label><label>每种物品独立掉率（%）<input v-model.number="itemPercent" aria-label="首领每种物品掉率" type="number" min="0" max="100" step="0.1" required></label></div><p>豪华掉落覆盖全部已上架装备、宝物、技能书、消耗品与材料，新增物品自动参与，停用或回收物品不掉落。宝石仅含各类一级宝石，各类分别随机数量，不掉落二至八级宝石。每种物品独立判定；普通目标掉落不受影响。</p><div class="boss-quantities"><label v-for="(name,key) in bossLootLabels" :key="key"><span>{{name}}每种数量</span><input v-model.number="form.quantities[key].min" type="number" min="1" :max="form.quantities[key].max" :aria-label="name+'数量下限'" required><span>～</span><input v-model.number="form.quantities[key].max" type="number" :min="form.quantities[key].min" max="100000" :aria-label="name+'数量上限'" required></label></div><button class="primary">保存首领规则</button></fieldset></form><button v-if="failed" :disabled="busy" @click="load">重新读取</button><p v-if="notice" class="toast" role="status">{{notice}}</p></section></template>
<style scoped>.boss-settings{padding:18px 20px;margin:18px 0;border:1px solid #8b4d3b;background:linear-gradient(120deg,#30221c,#151c14);box-shadow:inset 0 0 0 3px #10160e}.boss-settings h3{color:#edba70;margin:0 0 10px}.boss-settings p{color:#b9ab88;font-size:12px;line-height:1.8}.boss-settings fieldset{border:0;padding:0;min-width:0}.boss-controls{display:flex;gap:18px;align-items:end;flex-wrap:wrap}.boss-controls label{font-size:12px}.boss-controls input{width:110px;display:block;margin-top:7px}.boss-strength input{width:180px}.boss-settings h4{color:#dfbf80}.boss-controls .active{border-color:#be8a4c;color:#f6d48c}.boss-quantities{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 25px;margin:16px 0}.boss-quantities label{display:flex;align-items:center;gap:8px;font-size:12px;color:#d0bc86}.boss-quantities label>span:first-child{flex:1}.boss-quantities input{width:88px;margin:0}@media(max-width:680px){.boss-quantities{grid-template-columns:1fr}}</style>
